# Generated by Django 4.2.13 on 2024-05-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('marks', models.CharField(max_length=100, unique=True)),
                ('home_address', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
