# Generated by Django 4.2.13 on 2024-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.CharField(max_length=200),
        ),
    ]
